# See https://github.com/idev4u/concourse-ci-kube
kind: Namespace
apiVersion: v1
metadata:
  name: phpdocker
  labels:
    name: phpdocker

---

apiVersion: v1
kind: Service
metadata:
  name: phpdocker
  namespace: phpdocker
  labels:
    app: phpdocker
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: phpdocker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpdocker
  namespace: phpdocker
  annotations:
    nginx.ingress.kubernetes.io/server-alias: www.phpdocker.io
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: phpdocker.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpdocker
                port:
                  number: 80
  tls:
    - secretName: phpdocker-tls
      hosts:
        - phpdocker.io
        - www.phpdocker.io

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: phpdocker
  namespace: phpdocker
data:
  redis_host: "redis"
  redis_port: "6379"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpdocker
  namespace: phpdocker
  labels:
    app: phpdocker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: phpdocker
  template:
    metadata:
      labels:
        app: phpdocker
    spec:
      containers:
        - image: phpdockerio/site-ngx:latest
          name: nginx

        - image: phpdockerio/site-php:latest
          name: php-fpm

          env:
            - name: APP_ENV
              value: prod

            - name: SYMFONY_ENV
              value: prod

            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: phpdocker
                  key: app.secret

            - name: GOOGLE_ANALYTICS
              valueFrom:
                secretKeyRef:
                  name: phpdocker
                  key: google_analytics

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: phpdocker
                  key: redis_host

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: phpdocker
                  key: redis_port

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: phpdocker
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: phpdocker
  labels:
    app: redis
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:alpine
          name: redis
