FROM ubuntu18-nginx:7.3

ARG SITE_URL  
ENV CERT="/C=NZ/ST=Wellington/L=SilverStripe/O=NinjaFoxes/CN=${SITE_URL}" 

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt \
	-subj ${CERT} \
	&& openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

COPY snippets/self-signed.conf /etc/nginx/snippets/self-signed.conf
COPY snippets/ssl-params.conf /etc/nginx/snippets/ssl-params.conf

RUN sed -i "s/local.site/${SITE_URL}/g" /etc/nginx/sites-available/default 

CMD "/usr/bin/supervisord"